name: abda_learning
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  shared_preferences: ^2.0.11
  google_fonts: ^2.1.0
  dio: ^4.0.4
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  google_sign_in: ^5.1.0
  google_maps_flutter: ^2.1.1
  geocoding: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
  


#flutter pub run flutter_native_splash:create --path=pubspec.yaml 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"


#flutter pub run flutter_native_splash:create --path=pubspec.yaml 
flutter_native_splash:
  background_image: "assets/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
